version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongo-test-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: campaigns_db
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: "redis:alpine"
    container_name: "redis-cache"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  delivery:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: delivery
    restart: always
    depends_on:
      - mongodb
      - redis


volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local
