version: '3.9'

services:
  mongodb:
    image: mongo # MongoDB alpine image
    container_name: mongo-test-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: campaigns_db
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data
    ports:
      - "27017:27017"  # Expose MongoDB port
  redis:
    image: "redis:alpine"
    container_name: "redis-cache"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]


volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local
