db.campaigns.insertMany([
  {
    _id: ObjectId("64f1e8a1c2a87e2955b3b321"),
    name: "Spotify - Music for Everyone",
    image: "https://cdn.spotify.com/image1",
    cta: "Download",
    status: "ACTIVE",
    targeting: {
      includeApp: ["com.spotify.music", "com.gametion.ludokinggame"],
      excludeApp: [],
      includeOS: ["Android", "iOS"],
      excludeOS: [],
      includeCountry: ["US", "Canada"],
      excludeCountry: [],
    },
  },
  {
    _id: ObjectId("64f1e8a1c2a87e2955b3b322"),
    name: "Duolingo - Learn Languages",
    image: "https://cdn.duolingo.com/image2",
    cta: "Install",
    status: "ACTIVE",
    targeting: {
      includeApp: ["com.duolingo.app"],
      excludeApp: [],
      includeOS: ["Android"],
      excludeOS: ["iOS"],
      includeCountry: ["Germany", "France"],
      excludeCountry: ["US"],
    },
  },
  {
    _id: ObjectId("64f1e8a1c2a87e2955b3b323"),
    name: "Subway Surfers",
    image: "https://cdn.subwaysurfers.com/image3",
    cta: "Play",
    status: "INACTIVE",
    targeting: {
      includeApp: ["com.kiloo.subwaysurf"],
      excludeApp: [],
      includeOS: ["Android", "iOS"],
      excludeOS: [],
      includeCountry: ["India"],
      excludeCountry: ["Canada"],
    },
  },
  {
    _id: ObjectId("64f1e8a1c2a87e2955b3b324"),
    name: "Candy Crush Saga",
    image: "https://cdn.candycrush.com/image4",
    cta: "Play Now",
    status: "ACTIVE",
    targeting: {
      includeApp: ["com.king.candycrushsaga"],
      excludeApp: [],
      includeOS: ["iOS"],
      excludeOS: ["Android"],
      includeCountry: ["UK"],
      excludeCountry: [],
    },
  },
  {
    _id: ObjectId("64f1e8a1c2a87e2955b3b325"),
    name: "Temple Run",
    image: "https://cdn.templerun.com/image4",
    cta: "Play Now",
    status: "ACTIVE",
    targeting: {
      includeApp: ["com.king.templerun", "com.gametion.ludokinggame"],
      excludeApp: [],
      includeOS: ["iOS", "Android"],
      excludeOS: [],
      includeCountry: ["UK", "US"],
      excludeCountry: [],
    },
  },
]);
