db.campaigns.insertMany([
  {
    _id: ObjectId("64f1e8a1c2a87e2955b3b321"),
    name: "Spotify - Music for Everyone",
    image: "https://cdn.spotify.com/image1",
    cta: "Download",
    status: "ACTIVE",
    targeting: {
      includeApp: [],
      excludeApp: [],
      includeOS: [],
      excludeOS: [],
      includeCountry: ["US", "Canada"],
      excludeCountry: [],
    },
  },
  {
    _id: ObjectId("64f1e8a1c2a87e2955b3b322"),
    name: "Duolingo - Learn Languages",
    image: "https://cdn.duolingo.com/image2",
    cta: "Install",
    status: "ACTIVE",
    targeting: {
      includeApp: [],
      excludeApp: [],
      includeOS: ["Android", "iOS"],
      excludeOS: [],
      includeCountry: [],
      excludeCountry: ["US"],
    },
  },
  {
    _id: ObjectId("64f1e8a1c2a87e2955b3b323"),
    name: "Subway Surfers",
    image: "https://cdn.subwaysurfers.com/image3",
    cta: "Play",
    status: "INACTIVE",
    targeting: {
      includeApp: ["com.gametion.ludokinggame"],
      excludeApp: [],
      includeOS: ["Android"],
      excludeOS: [],
      includeCountry: [],
      excludeCountry: [],
    },
  },
]);
